from application import app
from util import session_manager

# X. Login(Create Session)
@app.route("/login", methods=['POST'])
def loginToPEP():
    def parseRequest():
        content = request.get_json()
        userId = content.get("userId")
        sessionKey = content.get("sessionKey") # Generated by Platform Manager
        return (userId, sessionKey)
    
    userId, sessionKey = parseRequest()
    result = login(userId, sessionKey)
    return result