#-*- coding: utf-8 -*-
from application import app
from util import session_manager
from flask import request
import yaml

# X. Login(Create Session)
@app.route("/login", methods=['POST'])
def loginToPEP():
    def parseRequest():
        content = yaml.safe_load(request.get_data())
        userId = content.get("userId")
        # sessionKey Generated by Platform Manager
        sessionKey = content.get("sessionKey")
        return (userId, sessionKey)
    
    userId, sessionKey = parseRequest()
    result = session_manager.login(userId, sessionKey)
    return result

